Repository pre-onboarding-12th-Team12/pre-onboarding-12th-1-12, pull requests merged in 2023-08, with the labels that each got.

#6 Fix, Chore: #5 프로젝트 빌드 경고, #7 프로젝트 build폴더 eslint 에러 해결
  .eslintignore
  package-lock.json
  package.json
Labels: bug, invalid

#12 Chore: pre-commit 수정
  .husky/pre-commit
Labels: 🌿Chore

#11 Feat, Design: ToDo 및 ToDoInput
  .github/ISSUE_TEMPLATE/♻️-refactor-.md
  .github/ISSUE_TEMPLATE/✅-feature-.md
  .github/ISSUE_TEMPLATE/🐞-bug-.md
  .github/pull_request_template.md
  package-lock.json
  src/api/requests.ts
  src/components/todo/ToDoInput.tsx
  src/components/todo/ToDoList.tsx
  src/pages/ToDo.tsx
  src/router/Router.tsx
  src/style/Common.tsx
  src/style/Layout.tsx
Labels: ✨Feature, 💄Design

#13 Design: 로그인, 회원가입 페이지 CSS 구현
  .github/ISSUE_TEMPLATE/♻️--refactor-.md
  .github/ISSUE_TEMPLATE/✨-feature-.md
  .github/ISSUE_TEMPLATE/🐞-bug-.md
  .github/pull_request_template.md
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/style/Common.ts
  src/style/Layout.ts
Labels: 💄Design

#16 Feature: 로그인 에러처리 및 로그아웃 추가
  src/api/requests.ts
  src/components/Signout.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/ToDo.tsx
Labels: ✨Feature

#15 Design: 랜딩페이지
  src/pages/Landing.tsx
  src/router/Router.tsx
  src/style/Layout.ts
Labels: 💄Design

#19 Refector: 인증, 인가 리펙토링
  src/components/Signout.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/ToDo.tsx
Labels: ♻️Refacor

#22 Fix: TodoInput 빈값 추가시 데이터요청 막기
  src/components/todo/ToDoInput.tsx
Labels: 🛠️Fix

#36 Feat: todoList merge
  package-lock.json
  package.json
  src/api/requests.ts
  src/components/todo/ToDoBoard.tsx
  src/components/todo/ToDoList.tsx
  src/components/todo/ToDoTask.tsx
  src/custom.d.ts
  src/images/checked.png
  src/pages/ToDo.tsx
  src/types.ts
  src/utils/sortedTodo.ts
Labels: ✨Feature
